---
- name: Add Mesosphere deb repository
  apt_repository:
    repo: "deb http://repos.mesosphere.com/ubuntu {{docker_ubuntu_name}} main"
    state: "present"
    update_cache: yes

- name: Install Mesos
  apt:
    name: "mesos={{mesos_version}}-0.2.145.ubuntu1504"
    state: "present"
    force: yes

- name: Set mesos-slave containerizers
  template: src=containerizers.j2 dest=/etc/mesos-slave/containerizers
  sudo: yes

- name: Set mesos-slave hostname
  template: src=hostname.j2 dest=/etc/mesos-slave/hostname
  sudo: yes

- name: Set mesos-slave config
  template: src=mesos-slave.j2 dest=/etc/default/mesos-slave
  sudo: yes

- name: restart mesos-slave
  service:
    name: mesos-slave
    state: restarted

- name: stop mesos-master
  service:
    name: mesos-master
    state: stopped
