---
- name: Get Docker release tool key
  apt_key: keyserver={{docker_keyserver}} id={{docker_keyserver_id}} state=present
  ignore_errors: yes

- name: Add Docker deb repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{docker_ubuntu_name}} main"
    state: "present"
    update_cache: yes

- name: Get kernel version
  command: uname -r
  register: docker_kernel_version
  changed_when: False

- name: Install linux-image-extra-$(uname -r)
  apt:
    name: "linux-image-extra-{{docker_kernel_version.stdout}}"
    state: "present"

# Install fixed version (http://www.ubuntuupdates.org/ppa/docker_new)
- name: Install Docker
  apt:
    name: "docker-engine={{docker_version}}-0~{{docker_ubuntu_name}}"
    state: "present"
